FROM node:18-alpine
WORKDIR /epns-showrunners-frameworks
COPY ../epns-showrunners-frameworks/node_modules /epns-showrunners-frameworks/node_modules
COPY . .
RUN ls
EXPOSE 5432
CMD ["sh", "runner.sh"]
