FROM node:18-alpine
WORKDIR /epns-showrunners-frameworks
COPY . .
RUN ls
RUN mkdir /epns-showrunners-frameworks/node_modules
RUN ls /epns-showrunners-frameworks/node_modules
COPY ../ /epns-showrunners-frameworks/node_modules
RUN ls 
EXPOSE 5432
CMD ["sh", "runner.sh"]
