name: TypeScript Lint

on:
  push:
    branches:
      - main 

jobs:
  lint:
    name: Run TypeScript Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npx eslint '**/*.ts' --max-warnings 0